import { useState } from 'react';
import { Recipe, ChildProfile } from '../../types';
import { usePlannedRecipes } from './usePlannedRecipes';
import { useRecipePlanning } from './useRecipePlanning';
import { format } from 'date-fns';
import { useRecipes } from '../../recipe/hooks/useRecipes';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export const useMealPlanner = (userId: string, selectedChildren: ChildProfile[]) => {
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [viewMode, setViewMode] = useState<'week' | 'month'>('week');
  
  const { recipes, loading: recipesLoading } = useRecipes(userId);
  const { 
    plannedRecipes, 
    loading: plannedRecipesLoading,
    updateLocalPlannedRecipes,
    removePlannedRecipeFromState,
    isAutoGenerated
  } = usePlannedRecipes(userId, selectedDate, viewMode, selectedChildren);
  
  const { planRecipe: planSingleRecipe, saving: planningRecipe } = useRecipePlanning();

  const loading = recipesLoading || plannedRecipesLoading;

  const planRecipe = async (recipe: Recipe, children: ChildProfile[]) => {
    const formattedDate = format(selectedDate, 'yyyy-MM-dd');
    for (const child of children) {
      try {
        await planSingleRecipe(recipe, children, selectedDate, userId);
        updateLocalPlannedRecipes(formattedDate, recipe, child.id);
      } catch (error) {
        console.error('Error planning recipe:', error);
      }
    }
  };

  const removeRecipe = (date: string, childId: string) => {
    removePlannedRecipeFromState(date, childId);
  };

  const validatePlanning = async () => {
    try {
      const { error } = await supabase
        .from('meal_plans')
        .update({ is_auto_generated: false })
        .eq('profile_id', userId)
        .eq('is_auto_generated', true);

      if (error) throw error;

      toast.success("Planning validé avec succès");
    } catch (error) {
      console.error('Error validating planning:', error);
      toast.error("Erreur lors de la validation du planning");
    }
  };

  return {
    selectedDate,
    setSelectedDate,
    recipes,
    plannedRecipes,
    loading,
    planningRecipe,
    planRecipe,
    removeRecipe,
    viewMode,
    setViewMode,
    isAutoGenerated,
    validatePlanning
  };
};