import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/components/ui/use-toast';
import { Recipe, ChildProfile } from '../../types';
import { format, startOfWeek, addDays, startOfMonth, endOfMonth } from 'date-fns';

interface PlannedRecipesByDate {
  [date: string]: {
    [childId: string]: Recipe;
  };
}

export const usePlannedRecipes = (
  userId: string,
  selectedDate: Date,
  viewMode: 'week' | 'month',
  selectedChildren: ChildProfile[]
) => {
  const [plannedRecipes, setPlannedRecipes] = useState<PlannedRecipesByDate>({});
  const [loading, setLoading] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const { toast } = useToast();

  const updateLocalPlannedRecipes = (date: string, recipe: Recipe, childId: string) => {
    setPlannedRecipes(prev => ({
      ...prev,
      [date]: {
        ...(prev[date] || {}),
        [childId]: recipe
      }
    }));
  };

  const removePlannedRecipeFromState = (date: string, childId: string) => {
    setPlannedRecipes(prev => {
      const newState = { ...prev };
      if (newState[date]) {
        const newDateState = { ...newState[date] };
        delete newDateState[childId];
        if (Object.keys(newDateState).length === 0) {
          delete newState[date];
        } else {
          newState[date] = newDateState;
        }
      }
      return newState;
    });
  };

  const parseRecipeData = (recipeData: any): Recipe => {
    return {
      ...recipeData,
      ingredients: Array.isArray(recipeData.ingredients) 
        ? recipeData.ingredients 
        : JSON.parse(typeof recipeData.ingredients === 'string' ? recipeData.ingredients : '[]'),
      nutritional_info: typeof recipeData.nutritional_info === 'string'
        ? JSON.parse(recipeData.nutritional_info)
        : recipeData.nutritional_info,
      health_benefits: typeof recipeData.health_benefits === 'string'
        ? JSON.parse(recipeData.health_benefits)
        : recipeData.health_benefits,
      cooking_steps: typeof recipeData.cooking_steps === 'string'
        ? JSON.parse(recipeData.cooking_steps)
        : recipeData.cooking_steps || []
    };
  };

  const fetchPlannedRecipes = async () => {
    setLoading(true);
    try {
      let startDate, endDate;
      
      if (viewMode === 'week') {
        startDate = startOfWeek(selectedDate, { weekStartsOn: 1 });
        endDate = addDays(startDate, 6);
      } else {
        startDate = startOfMonth(selectedDate);
        endDate = endOfMonth(selectedDate);
      }

      const query = supabase
        .from('meal_plans')
        .select('*, recipes(*)')
        .eq('profile_id', userId)
        .gte('date', format(startDate, 'yyyy-MM-dd'))
        .lte('date', format(endDate, 'yyyy-MM-dd'));

      if (selectedChildren.length > 0) {
        query.in('child_id', selectedChildren.map(child => child.id));
      }

      const { data, error } = await query;

      if (error) throw error;

      const plannedRecipeMap: PlannedRecipesByDate = {};
      let hasAutoGenerated = false;
      
      data.forEach(plan => {
        if (plan.recipes && plan.child_id) {
          const date = plan.date;
          if (!plannedRecipeMap[date]) {
            plannedRecipeMap[date] = {};
          }
          plannedRecipeMap[date][plan.child_id] = parseRecipeData(plan.recipes);
          if (plan.is_auto_generated) {
            hasAutoGenerated = true;
          }
        }
      });

      setIsAutoGenerated(hasAutoGenerated);
      setPlannedRecipes(plannedRecipeMap);
    } catch (error) {
      console.error('Error fetching planned recipes:', error);
      toast({
        title: "Erreur",
        description: "Impossible de charger les recettes planifiées",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPlannedRecipes();
  }, [selectedDate, viewMode, selectedChildren]);

  return { 
    plannedRecipes, 
    loading, 
    updateLocalPlannedRecipes, 
    fetchPlannedRecipes,
    removePlannedRecipeFromState,
    isAutoGenerated
  };
};