import { Card } from '@/components/ui/card';
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { CalendarDays, CalendarRange } from "lucide-react";
import { WeeklyCalendar } from '../meal-planner/WeeklyCalendar';
import { Recipe, ChildProfile } from '../types';

interface PlannerCalendarProps {
  selectedDate: Date;
  setSelectedDate: (date: Date) => void;
  plannedRecipes: { [key: string]: { [childId: string]: Recipe } };
  viewMode: 'week' | 'month';
  setViewMode: (mode: 'week' | 'month') => void;
  selectedChildren: ChildProfile[];
  onRemoveRecipe: (date: string, childId: string) => void;
  isAutoGenerated: boolean;
}

export const PlannerCalendar = ({
  selectedDate,
  setSelectedDate,
  plannedRecipes,
  viewMode,
  setViewMode,
  selectedChildren,
  onRemoveRecipe,
  isAutoGenerated
}: PlannerCalendarProps) => {
  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 w-full md:w-auto">
        <ToggleGroup 
          type="single" 
          value={viewMode} 
          onValueChange={(value) => value && setViewMode(value as 'week' | 'month')} 
          className="justify-start"
        >
          <ToggleGroupItem value="week" aria-label="Vue semaine">
            <CalendarDays className="h-4 w-4" />
            <span className="ml-2">Semaine</span>
          </ToggleGroupItem>
          <ToggleGroupItem value="month" aria-label="Vue mois">
            <CalendarRange className="h-4 w-4" />
            <span className="ml-2">Mois</span>
          </ToggleGroupItem>
        </ToggleGroup>
      </div>

      <Card className="p-4">
        <WeeklyCalendar
          selectedDate={selectedDate}
          onSelectDate={setSelectedDate}
          plannedRecipes={plannedRecipes}
          viewMode={viewMode}
          selectedChildren={selectedChildren}
          onRemoveRecipe={onRemoveRecipe}
          isAutoGenerated={isAutoGenerated}
        />
      </Card>
    </div>
  );
};