// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqmwyaazsozedazrvmfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxbXd5YWF6c296ZWRhenJ2bWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NjgwODIsImV4cCI6MjA1MjM0NDA4Mn0.7OChsuf9MclMAkjxEKjVKXm7_1_lOpZoXZavyWj8kI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);